hash-format = "sha256"

[[files]]
file = "config/paxi/resourcepacks/refined-cats.pw.toml"
metafile = true

[[files]]
file = "mods/content/applied-energistics/ae2-qol-recipes.pw.toml"
metafile = true

[[files]]
file = "mods/content/applied-energistics/ae2.pw.toml"
metafile = true

[[files]]
file = "mods/content/applied-energistics/applied-energistics-2-wireless-terminals.pw.toml"
metafile = true

[[files]]
file = "mods/content/computer-craft/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/bellsandwhistles.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/copycats.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-central-kitchen.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-dragons-plus.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-enchantable-machinery.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-enchantment-industry.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-integrated-farming.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-more-pipe-bombs-in-packages.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-pattern-schematics.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-power-loader.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-railways-navigator.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-sound-of-steam.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-stock-bridge.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-trading-floor.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/escalated.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/hypertube.pw.toml"
metafile = true

[[files]]
file = "mods/content/exposure/exposure-catalog.pw.toml"
metafile = true

[[files]]
file = "mods/content/exposure/exposure-expanded.pw.toml"
metafile = true

[[files]]
file = "mods/content/exposure/exposure-polaroid.pw.toml"
metafile = true

[[files]]
file = "mods/content/exposure/exposure.pw.toml"
metafile = true

[[files]]
file = "mods/content/farmers-delight/farmers-delight.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/creeper-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/enderman-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/content/other/joy-of-painting.pw.toml"
metafile = true

[[files]]
file = "mods/content/other/mmmmmmmmmmmm.pw.toml"
metafile = true

[[files]]
file = "mods/content/other/music-maker-mod.pw.toml"
metafile = true

[[files]]
file = "mods/content/other/straw-statues.pw.toml"
metafile = true

[[files]]
file = "mods/content/silly/moyai.pw.toml"
metafile = true

[[files]]
file = "mods/content/silly/mystical-oak-tree.pw.toml"
metafile = true

[[files]]
file = "mods/content/supplementaries/amendments.pw.toml"
metafile = true

[[files]]
file = "mods/content/supplementaries/supplementaries-squared.pw.toml"
metafile = true

[[files]]
file = "mods/content/supplementaries/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/collective.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/connector.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/forgified-fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/guideme.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/kiwi.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/kotlin-for-forge.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/patchouli.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/mimi.pw.toml"
metafile = true

[[files]]
file = "mods/performance/c2me-neoforge.pw.toml"
metafile = true

[[files]]
file = "mods/performance/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/performance/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/performance/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/performance/krypton-foxified.pw.toml"
metafile = true

[[files]]
file = "mods/performance/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/performance/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/performance/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/performance/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/emi/emi.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/emi/extra-mod-integrations.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/armor-statues.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/cat_jam.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/crawl.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/grass-seeds.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/ironfish.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/lootr.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/no-enderman-grief.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/passable-foliage.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/screenshot-to-clipboard.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/skippy-pearls.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/snow-under-trees.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/softer-hay-bales.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/treechop.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/vivecraft.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/better-ping-display.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/chat-heads.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/jade.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/modelfix.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/seamless-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/bettergrassify.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/distanthorizons.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/particular-reforged.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/visuality-forge.pw.toml"
metafile = true

[[files]]
file = "mods/utilities/bluemap/bluemap.pw.toml"
metafile = true

[[files]]
file = "mods/utilities/bluemap/create-track-map-fork.pw.toml"
metafile = true

[[files]]
file = "mods/utilities/chunky.pw.toml"
metafile = true

[[files]]
file = "mods/utilities/spark.pw.toml"
metafile = true

[[files]]
file = "mods/utilities/xaeros/xaero-train-map.pw.toml"
metafile = true

[[files]]
file = "mods/utilities/xaeros/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/utilities/xaeros/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "unsup.toml"
