hash-format = "sha256"

[[files]]
file = "config/craftpresence.json"

[[files]]
file = "config/vivecraft-client-config.json"
preserve = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/craftmine-fixes.pw.toml"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
metafile = true

[[files]]
file = "mods/exchange-value-tracker.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
metafile = true

[[files]]
file = "mods/physical-falling-trees.pw.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
metafile = true

[[files]]
file = "mods/vivecraft.pw.toml"
metafile = true

[[files]]
file = "servers.dat"
