hash-format = "sha256"

[[files]]
file = "config/paxi/resourcepacks/refined-cats.pw.toml"
metafile = true

[[files]]
file = "mods/create.pw.toml"
metafile = true

[[files]]
file = "mods/gregtechceu-modern.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/paxi.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/yungs-api.pw.toml"
metafile = true

[[files]]
file = "mods/valkyrien-skies.pw.toml"
metafile = true

[[files]]
file = "mods/valkyrien-space-war.pw.toml"
metafile = true

[[files]]
file = "unsup.toml"
