[flavor_groups.map]
name = "Map mod"
side = "client"
choices = [
  { id = "map_xaero", name = "Xaero" },
  { id = "map_journey", name = "Journey" },
]

[flavor_groups.dh]
name = "Distant Horizons"
side = "client"
choices = [
  { id = "dh_on", name = "Enabled" },
  { id = "dh_off", name = "Disabled" },
]

[flavor_groups.iris]
name = "Iris"
side = "client"
choices = [
  { id = "iris_on", name = "Enabled" },
  { id = "iris_off", name = "Disabled" },
]

[flavor_groups.particular]
name = "Particular"
side = "client"
choices = [
  { id = "particular_on", name = "Enabled" },
  { id = "particular_off", name = "Disabled" },
]

[flavor_groups.visuality]
name = "Visuality"
side = "client"
choices = [
  { id = "visuality_on", name = "Enabled" },
  { id = "visuality_off", name = "Disabled" },
]

[flavor_groups.dynamic]
name = "Dynamic Lights"
side = "client"
choices = [
  { id = "dynamic_on", name = "Enabled" },
  { id = "dynamic_off", name = "Disabled" },
]

[metafile]
xaero-train-map.flavors = ["map_xaero"]
xaeros-minimap.flavors = ["map_xaero"]
xaeros-world-map.flavors = ["map_xaero"]

journeylocator.flavors = ["map_journey"]
journeymap.flavors = ["map_journey"]

distanthorizons.flavors = ["dh_on"]

colorwheel-patcher.flavors = ["iris_on"]
colorwheel.flavors = ["iris_on"]
euphoria-patches.flavors = ["iris_on"]
iris.flavors = ["iris_on"]
complementary-reimagined.flavors = ["iris_on"]
complementary-unbound.flavors = ["iris_on"]

particular-reforged.flavors = ["particular_on"]

visuality-forge.flavors = ["visuality_on"]

sodium-dynamic-lights.flavors = ["dynamic_on"]
